name: Carolina Exclusive Living
favicon: null
layout_spectrum: 0.10481
typography_spectrum: 0.91297
title: Carolina Exclusive Living
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fdfdff'
    - '#c2cee8'
    - '#232227'
    - '#656469'
    - '#908f94'
  brandStrength: 0.625
  lightness: 0.6875
  saturation: 0.4375
  rhythmicContrast: 0
purpose: []
